image: node:18-alpine

stages:
  - build
  - deploy

build_app:
  stage: build
  script:
    - echo "Instalando dependencias..."
    - npm install
    - echo "Compilando la aplicaci칩n Vue.js..."
    - npm run build
  artifacts:
    paths:
      - dist/ # Guarda la carpeta dist/ como artefacto para la siguiente etapa
    expire_in: 1 day

# Job para la etapa de despliegue en GitLab Pages
pages:
  stage: deploy
  script:
    - echo "Moviendo archivos compilados a la ubicaci칩n de GitLab Pages..."
    - mv dist/ public/ # GitLab Pages busca los archivos est치ticos en una carpeta llamada 'public/'
  artifacts:
    paths:
      - public # Define 'public/' como la carpeta que GitLab Pages desplegar치
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH